// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeapproveSuggestionPayload")
public inline fun approveSuggestionPayload(block: com.dare.music.listentogether.proto.ApproveSuggestionPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload =
  com.dare.music.listentogether.proto.ApproveSuggestionPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.ApproveSuggestionPayload`
 */
public object ApproveSuggestionPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload = _builder.build()

    /**
     * `string suggestion_id = 1;`
     */
    public var suggestionId: kotlin.String
      @kotlin.jvm.JvmName("getSuggestionId")
        get() = _builder.suggestionId
      @kotlin.jvm.JvmName("setSuggestionId")
        set(value) {
        _builder.suggestionId = value
      }
    /**
     * `string suggestion_id = 1;`
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload.copy(block: `com.dare.music.listentogether.proto`.ApproveSuggestionPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.ApproveSuggestionPayload =
  `com.dare.music.listentogether.proto`.ApproveSuggestionPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

