// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializebufferWaitPayload")
public inline fun bufferWaitPayload(block: com.dare.music.listentogether.proto.BufferWaitPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload =
  com.dare.music.listentogether.proto.BufferWaitPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.BufferWaitPayload`
 */
public object BufferWaitPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload = _builder.build()

    /**
     * `string track_id = 1;`
     */
    public var trackId: kotlin.String
      @kotlin.jvm.JvmName("getTrackId")
        get() = _builder.trackId
      @kotlin.jvm.JvmName("setTrackId")
        set(value) {
        _builder.trackId = value
      }
    /**
     * `string track_id = 1;`
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WaitingForProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string waiting_for = 2;`
     * @return A list containing the waitingFor.
     */
    public val waitingFor: com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.waitingForList
      )
    /**
     * `repeated string waiting_for = 2;`
     * @param value The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addWaitingFor")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.add(value: kotlin.String) {
      _builder.addWaitingFor(value)
    }
    /**
     * `repeated string waiting_for = 2;`
     * @param value The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignWaitingFor")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string waiting_for = 2;`
     * @param values The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllWaitingFor")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllWaitingFor(values)
    }
    /**
     * `repeated string waiting_for = 2;`
     * @param values The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllWaitingFor")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string waiting_for = 2;`
     * @param index The index to set the value at.
     * @param value The waitingFor to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setWaitingFor")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setWaitingFor(index, value)
    }/**
     * `repeated string waiting_for = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setWaitingFor")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.clear() {
      _builder.clearWaitingFor()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload.copy(block: `com.dare.music.listentogether.proto`.BufferWaitPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.BufferWaitPayload =
  `com.dare.music.listentogether.proto`.BufferWaitPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

