// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeclientCapabilities")
public inline fun clientCapabilities(block: com.dare.music.listentogether.proto.ClientCapabilitiesKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.ClientCapabilities =
  com.dare.music.listentogether.proto.ClientCapabilitiesKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.ClientCapabilities.newBuilder()).apply { block() }._build()
/**
 * ```
 * Capability negotiation (first message from client)
 * ```
 *
 * Protobuf type `listentogether.ClientCapabilities`
 */
public object ClientCapabilitiesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.ClientCapabilities.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.ClientCapabilities.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.ClientCapabilities = _builder.build()

    /**
     * `bool supports_protobuf = 1;`
     */
    public var supportsProtobuf: kotlin.Boolean
      @kotlin.jvm.JvmName("getSupportsProtobuf")
        get() = _builder.supportsProtobuf
      @kotlin.jvm.JvmName("setSupportsProtobuf")
        set(value) {
        _builder.supportsProtobuf = value
      }
    /**
     * `bool supports_protobuf = 1;`
     */
    public fun clearSupportsProtobuf() {
      _builder.clearSupportsProtobuf()
    }

    /**
     * `bool supports_compression = 2;`
     */
    public var supportsCompression: kotlin.Boolean
      @kotlin.jvm.JvmName("getSupportsCompression")
        get() = _builder.supportsCompression
      @kotlin.jvm.JvmName("setSupportsCompression")
        set(value) {
        _builder.supportsCompression = value
      }
    /**
     * `bool supports_compression = 2;`
     */
    public fun clearSupportsCompression() {
      _builder.clearSupportsCompression()
    }

    /**
     * `string client_version = 3;`
     */
    public var clientVersion: kotlin.String
      @kotlin.jvm.JvmName("getClientVersion")
        get() = _builder.clientVersion
      @kotlin.jvm.JvmName("setClientVersion")
        set(value) {
        _builder.clientVersion = value
      }
    /**
     * `string client_version = 3;`
     */
    public fun clearClientVersion() {
      _builder.clearClientVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.ClientCapabilities.copy(block: `com.dare.music.listentogether.proto`.ClientCapabilitiesKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.ClientCapabilities =
  `com.dare.music.listentogether.proto`.ClientCapabilitiesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

