// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeenvelope")
public inline fun envelope(block: com.dare.music.listentogether.proto.EnvelopeKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.Envelope =
  com.dare.music.listentogether.proto.EnvelopeKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.Envelope.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message envelope with type and payload
 * ```
 *
 * Protobuf type `listentogether.Envelope`
 */
public object EnvelopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.Envelope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.Envelope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.Envelope = _builder.build()

    /**
     * `string type = 1;`
     */
    public var type: kotlin.String
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `string type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `bytes payload = 2;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * `bytes payload = 2;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * ```
     * Indicates if payload is gzip compressed
     * ```
     *
     * `bool compressed = 3;`
     */
    public var compressed: kotlin.Boolean
      @kotlin.jvm.JvmName("getCompressed")
        get() = _builder.compressed
      @kotlin.jvm.JvmName("setCompressed")
        set(value) {
        _builder.compressed = value
      }
    /**
     * ```
     * Indicates if payload is gzip compressed
     * ```
     *
     * `bool compressed = 3;`
     */
    public fun clearCompressed() {
      _builder.clearCompressed()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.Envelope.copy(block: `com.dare.music.listentogether.proto`.EnvelopeKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.Envelope =
  `com.dare.music.listentogether.proto`.EnvelopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

