// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializehostChangedPayload")
public inline fun hostChangedPayload(block: com.dare.music.listentogether.proto.HostChangedPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.HostChangedPayload =
  com.dare.music.listentogether.proto.HostChangedPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.HostChangedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.HostChangedPayload`
 */
public object HostChangedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.HostChangedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.HostChangedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.HostChangedPayload = _builder.build()

    /**
     * `string new_host_id = 1;`
     */
    public var newHostId: kotlin.String
      @kotlin.jvm.JvmName("getNewHostId")
        get() = _builder.newHostId
      @kotlin.jvm.JvmName("setNewHostId")
        set(value) {
        _builder.newHostId = value
      }
    /**
     * `string new_host_id = 1;`
     */
    public fun clearNewHostId() {
      _builder.clearNewHostId()
    }

    /**
     * `string new_host_name = 2;`
     */
    public var newHostName: kotlin.String
      @kotlin.jvm.JvmName("getNewHostName")
        get() = _builder.newHostName
      @kotlin.jvm.JvmName("setNewHostName")
        set(value) {
        _builder.newHostName = value
      }
    /**
     * `string new_host_name = 2;`
     */
    public fun clearNewHostName() {
      _builder.clearNewHostName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.HostChangedPayload.copy(block: `com.dare.music.listentogether.proto`.HostChangedPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.HostChangedPayload =
  `com.dare.music.listentogether.proto`.HostChangedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

