// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializejoinApprovedPayload")
public inline fun joinApprovedPayload(block: com.dare.music.listentogether.proto.JoinApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload =
  com.dare.music.listentogether.proto.JoinApprovedPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.JoinApprovedPayload`
 */
public object JoinApprovedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload = _builder.build()

    /**
     * `string room_code = 1;`
     */
    public var roomCode: kotlin.String
      @kotlin.jvm.JvmName("getRoomCode")
        get() = _builder.roomCode
      @kotlin.jvm.JvmName("setRoomCode")
        set(value) {
        _builder.roomCode = value
      }
    /**
     * `string room_code = 1;`
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * `string user_id = 2;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 2;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string session_token = 3;`
     */
    public var sessionToken: kotlin.String
      @kotlin.jvm.JvmName("getSessionToken")
        get() = _builder.sessionToken
      @kotlin.jvm.JvmName("setSessionToken")
        set(value) {
        _builder.sessionToken = value
      }
    /**
     * `string session_token = 3;`
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }

    /**
     * `.listentogether.RoomState state = 4;`
     */
    public var state: com.dare.music.listentogether.proto.Listentogether.RoomState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    /**
     * `.listentogether.RoomState state = 4;`
     */
    public fun clearState() {
      _builder.clearState()
    }
    /**
     * `.listentogether.RoomState state = 4;`
     * @return Whether the state field is set.
     */
    public fun hasState(): kotlin.Boolean {
      return _builder.hasState()
    }

    public val JoinApprovedPayloadKt.Dsl.stateOrNull: com.dare.music.listentogether.proto.Listentogether.RoomState?
      get() = _builder.stateOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload.copy(block: `com.dare.music.listentogether.proto`.JoinApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayload =
  `com.dare.music.listentogether.proto`.JoinApprovedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.dare.music.listentogether.proto.Listentogether.JoinApprovedPayloadOrBuilder.stateOrNull: com.dare.music.listentogether.proto.Listentogether.RoomState?
  get() = if (hasState()) getState() else null

