// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeplaybackActionPayload")
public inline fun playbackActionPayload(block: com.dare.music.listentogether.proto.PlaybackActionPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload =
  com.dare.music.listentogether.proto.PlaybackActionPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.PlaybackActionPayload`
 */
public object PlaybackActionPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload = _builder.build()

    /**
     * `string action = 1;`
     */
    public var action: kotlin.String
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `string action = 1;`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * `string track_id = 2;`
     */
    public var trackId: kotlin.String
      @kotlin.jvm.JvmName("getTrackId")
        get() = _builder.trackId
      @kotlin.jvm.JvmName("setTrackId")
        set(value) {
        _builder.trackId = value
      }
    /**
     * `string track_id = 2;`
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }

    /**
     * `int64 position = 3;`
     */
    public var position: kotlin.Long
      @kotlin.jvm.JvmName("getPosition")
        get() = _builder.position
      @kotlin.jvm.JvmName("setPosition")
        set(value) {
        _builder.position = value
      }
    /**
     * `int64 position = 3;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }

    /**
     * `.listentogether.TrackInfo track_info = 4;`
     */
    public var trackInfo: com.dare.music.listentogether.proto.Listentogether.TrackInfo
      @kotlin.jvm.JvmName("getTrackInfo")
        get() = _builder.trackInfo
      @kotlin.jvm.JvmName("setTrackInfo")
        set(value) {
        _builder.trackInfo = value
      }
    /**
     * `.listentogether.TrackInfo track_info = 4;`
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * `.listentogether.TrackInfo track_info = 4;`
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }

    public val PlaybackActionPayloadKt.Dsl.trackInfoOrNull: com.dare.music.listentogether.proto.Listentogether.TrackInfo?
      get() = _builder.trackInfoOrNull

    /**
     * `bool insert_next = 5;`
     */
    public var insertNext: kotlin.Boolean
      @kotlin.jvm.JvmName("getInsertNext")
        get() = _builder.insertNext
      @kotlin.jvm.JvmName("setInsertNext")
        set(value) {
        _builder.insertNext = value
      }
    /**
     * `bool insert_next = 5;`
     */
    public fun clearInsertNext() {
      _builder.clearInsertNext()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QueueProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     */
     public val queue: com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.queueList
      )
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addQueue")
    public fun com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.add(value: com.dare.music.listentogether.proto.Listentogether.TrackInfo) {
      _builder.addQueue(value)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(value: com.dare.music.listentogether.proto.Listentogether.TrackInfo) {
      add(value)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllQueue")
    public fun com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.addAll(values: kotlin.collections.Iterable<com.dare.music.listentogether.proto.Listentogether.TrackInfo>) {
      _builder.addAllQueue(values)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(values: kotlin.collections.Iterable<com.dare.music.listentogether.proto.Listentogether.TrackInfo>) {
      addAll(values)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     * @param index The index to set the value at.
     * @param value The queue to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setQueue")
    public operator fun com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.set(index: kotlin.Int, value: com.dare.music.listentogether.proto.Listentogether.TrackInfo) {
      _builder.setQueue(index, value)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 6;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearQueue")
    public fun com.google.protobuf.kotlin.DslList<com.dare.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.clear() {
      _builder.clearQueue()
    }

    /**
     * `string queue_title = 7;`
     */
    public var queueTitle: kotlin.String
      @kotlin.jvm.JvmName("getQueueTitle")
        get() = _builder.queueTitle
      @kotlin.jvm.JvmName("setQueueTitle")
        set(value) {
        _builder.queueTitle = value
      }
    /**
     * `string queue_title = 7;`
     */
    public fun clearQueueTitle() {
      _builder.clearQueueTitle()
    }

    /**
     * `float volume = 8;`
     */
    public var volume: kotlin.Float
      @kotlin.jvm.JvmName("getVolume")
        get() = _builder.volume
      @kotlin.jvm.JvmName("setVolume")
        set(value) {
        _builder.volume = value
      }
    /**
     * `float volume = 8;`
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * `int64 server_time = 9;`
     */
    public var serverTime: kotlin.Long
      @kotlin.jvm.JvmName("getServerTime")
        get() = _builder.serverTime
      @kotlin.jvm.JvmName("setServerTime")
        set(value) {
        _builder.serverTime = value
      }
    /**
     * `int64 server_time = 9;`
     */
    public fun clearServerTime() {
      _builder.clearServerTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload.copy(block: `com.dare.music.listentogether.proto`.PlaybackActionPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayload =
  `com.dare.music.listentogether.proto`.PlaybackActionPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.dare.music.listentogether.proto.Listentogether.PlaybackActionPayloadOrBuilder.trackInfoOrNull: com.dare.music.listentogether.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

