// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializesuggestionRejectedPayload")
public inline fun suggestionRejectedPayload(block: com.dare.music.listentogether.proto.SuggestionRejectedPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload =
  com.dare.music.listentogether.proto.SuggestionRejectedPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.SuggestionRejectedPayload`
 */
public object SuggestionRejectedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload = _builder.build()

    /**
     * `string suggestion_id = 1;`
     */
    public var suggestionId: kotlin.String
      @kotlin.jvm.JvmName("getSuggestionId")
        get() = _builder.suggestionId
      @kotlin.jvm.JvmName("setSuggestionId")
        set(value) {
        _builder.suggestionId = value
      }
    /**
     * `string suggestion_id = 1;`
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * `string reason = 2;`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 2;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload.copy(block: `com.dare.music.listentogether.proto`.SuggestionRejectedPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.SuggestionRejectedPayload =
  `com.dare.music.listentogether.proto`.SuggestionRejectedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

