// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializetrackInfo")
public inline fun trackInfo(block: com.dare.music.listentogether.proto.TrackInfoKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.TrackInfo =
  com.dare.music.listentogether.proto.TrackInfoKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.TrackInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * Track information
 * ```
 *
 * Protobuf type `listentogether.TrackInfo`
 */
public object TrackInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.TrackInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.TrackInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.TrackInfo = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string title = 2;`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 2;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `string artist = 3;`
     */
    public var artist: kotlin.String
      @kotlin.jvm.JvmName("getArtist")
        get() = _builder.artist
      @kotlin.jvm.JvmName("setArtist")
        set(value) {
        _builder.artist = value
      }
    /**
     * `string artist = 3;`
     */
    public fun clearArtist() {
      _builder.clearArtist()
    }

    /**
     * `string album = 4;`
     */
    public var album: kotlin.String
      @kotlin.jvm.JvmName("getAlbum")
        get() = _builder.album
      @kotlin.jvm.JvmName("setAlbum")
        set(value) {
        _builder.album = value
      }
    /**
     * `string album = 4;`
     */
    public fun clearAlbum() {
      _builder.clearAlbum()
    }

    /**
     * `int64 duration = 5;`
     */
    public var duration: kotlin.Long
      @kotlin.jvm.JvmName("getDuration")
        get() = _builder.duration
      @kotlin.jvm.JvmName("setDuration")
        set(value) {
        _builder.duration = value
      }
    /**
     * `int64 duration = 5;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }

    /**
     * `string thumbnail = 6;`
     */
    public var thumbnail: kotlin.String
      @kotlin.jvm.JvmName("getThumbnail")
        get() = _builder.thumbnail
      @kotlin.jvm.JvmName("setThumbnail")
        set(value) {
        _builder.thumbnail = value
      }
    /**
     * `string thumbnail = 6;`
     */
    public fun clearThumbnail() {
      _builder.clearThumbnail()
    }

    /**
     * `string suggested_by = 7;`
     */
    public var suggestedBy: kotlin.String
      @kotlin.jvm.JvmName("getSuggestedBy")
        get() = _builder.suggestedBy
      @kotlin.jvm.JvmName("setSuggestedBy")
        set(value) {
        _builder.suggestedBy = value
      }
    /**
     * `string suggested_by = 7;`
     */
    public fun clearSuggestedBy() {
      _builder.clearSuggestedBy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.TrackInfo.copy(block: `com.dare.music.listentogether.proto`.TrackInfoKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.TrackInfo =
  `com.dare.music.listentogether.proto`.TrackInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

