// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializetransferHostPayload")
public inline fun transferHostPayload(block: com.dare.music.listentogether.proto.TransferHostPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.TransferHostPayload =
  com.dare.music.listentogether.proto.TransferHostPayloadKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.TransferHostPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.TransferHostPayload`
 */
public object TransferHostPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.TransferHostPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.TransferHostPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.TransferHostPayload = _builder.build()

    /**
     * `string new_host_id = 1;`
     */
    public var newHostId: kotlin.String
      @kotlin.jvm.JvmName("getNewHostId")
        get() = _builder.newHostId
      @kotlin.jvm.JvmName("setNewHostId")
        set(value) {
        _builder.newHostId = value
      }
    /**
     * `string new_host_id = 1;`
     */
    public fun clearNewHostId() {
      _builder.clearNewHostId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.TransferHostPayload.copy(block: `com.dare.music.listentogether.proto`.TransferHostPayloadKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.TransferHostPayload =
  `com.dare.music.listentogether.proto`.TransferHostPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

