// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.dare.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeuserInfo")
public inline fun userInfo(block: com.dare.music.listentogether.proto.UserInfoKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.UserInfo =
  com.dare.music.listentogether.proto.UserInfoKt.Dsl._create(com.dare.music.listentogether.proto.Listentogether.UserInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * User information
 * ```
 *
 * Protobuf type `listentogether.UserInfo`
 */
public object UserInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.dare.music.listentogether.proto.Listentogether.UserInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.dare.music.listentogether.proto.Listentogether.UserInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.dare.music.listentogether.proto.Listentogether.UserInfo = _builder.build()

    /**
     * `string user_id = 1;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string username = 2;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 2;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `bool is_host = 3;`
     */
    public var isHost: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsHost")
        get() = _builder.isHost
      @kotlin.jvm.JvmName("setIsHost")
        set(value) {
        _builder.isHost = value
      }
    /**
     * `bool is_host = 3;`
     */
    public fun clearIsHost() {
      _builder.clearIsHost()
    }

    /**
     * `bool is_connected = 4;`
     */
    public var isConnected: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsConnected")
        get() = _builder.isConnected
      @kotlin.jvm.JvmName("setIsConnected")
        set(value) {
        _builder.isConnected = value
      }
    /**
     * `bool is_connected = 4;`
     */
    public fun clearIsConnected() {
      _builder.clearIsConnected()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.dare.music.listentogether.proto.Listentogether.UserInfo.copy(block: `com.dare.music.listentogether.proto`.UserInfoKt.Dsl.() -> kotlin.Unit): com.dare.music.listentogether.proto.Listentogether.UserInfo =
  `com.dare.music.listentogether.proto`.UserInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

